### ISSUE TITLE
support for translate

### ISSUE THREAD

**Issue by keertijoshi** [remotty/angular-ladda#17]
Does angular-ladda support the usage of angular-translate?

**Comment by andreialecu** [comment]
Apparently there is an issue with using the `translate` attribute on the `button` directly, but if you layer it like this:

```html
<button ladda='...'>
<span translate="TRANSLATION_ID"></span>
</button>
```

It will work.

**Comment by andreialecu** [comment]
The problem is that the spinner is missing unless the HTML is layered like in my above comment.

The problem is here:
https://github.com/remotty/angular-ladda/blob/master/src/angular-ladda.js#L61

`element.contents()` will be empty because angular-translate didn't get a chance to insert the translation yet. I also suspect angular-translate is overwriting the contents afterwards because the inner `ladda-label` span disappears. 

I'm not sure what the best fix here is, perhaps it would be as simple as wrapping the `link` function in a `$timeout` so it runs after angular-translate finished its manipulation.

**Comment by cristiano2lopes** [comment]
Yep. Also happens with angular-gettext

**Comment by subicura** [comment]
@andreialecu @cristiano2lopes Hello! 

It is difficult problem. If you use $timeout, it seems work fine. But ladda is not working after change language. 
Angular-translate overwrite ladda element when change language(`$translate.use(key);`).
So you should not use attribute direct to ladda element. 

I prefer use another way.

```
<!-- OK -->
<button id="btn" ladda="isLoading" ng-click="isLoading = true" class="btn btn-primary">{{ 'TITLE' | translate }}</button>
<!-- fail -->
<button id="btn" ladda="isLoading" ng-click="isLoading = true" class="btn btn-primary" translate>TITLE</button>
<!-- fail -->
<button id="btn" ladda="isLoading" ng-click="isLoading = true" class="btn btn-primary" translate="TITLE"></button>
```

Please let me know, if you have any other idea. Thank you!
